name: Python tests

on: [push]

jobs: # jobs run in parallel. individual steps within a job do not.
  build-and-test: # arbitrary name
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # the matrix strategy takes essentially a cartesian product of these options
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build and install
      shell: bash # not cmd/powershell that windows uses
      run: |
        python -m pip install --upgrade pip build
        cd python
        python -m build --wheel
        python -m pip install dist/*.whl
        cd ..
    - name: Run tests
      shell: bash
      run: | # pytest with no args. if it fails with a nonzero status code, that *should* pop up as a failure in Github's statuses
        cd python/tests
        python -m pip install -r requirements.txt
        pytest
